version: '3'

services:
  db:
    image: db_6tm:latest
    container_name: db_6tm_cont
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: photoapi
    ports:
      - "3306:3306"
    volumes:
      - ./data.sql:/docker-entrypoint-initdb.d/data.sql